language: node_js
node_js:
- '8'
before_install:
- npm i -g npm@6.1.0
install:
- travis_wait npm install
script:
- npm run lint
- npm run unit
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_0d22c88004c9_key -iv $encrypted_0d22c88004c9_iv
  -in aepp-identity-deploy.enc -out aepp-identity-deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 aepp-identity-deploy
- ssh-add aepp-identity-deploy
- mkdir -p ~/.ssh
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/identity.aepps.com/
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/stage-identity.aepps.com/
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ssh deploy@139.59.142.164 "mkdir -p /var/www/html/BRANCHES.origin.aepps.com/`echo $TRAVIS_BRANCH | tr '[:punct:]' '-'`/" && rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/BRANCHES.origin.aepps.com/`echo $TRAVIS_BRANCH | tr '[:punct:]' '-'`
    on:
      all_branches: true
